# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-13 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20170517_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='pic_folder/None/no-img.jpg', upload_to='photos/%Y/%m/%d/%s'),
        ),
        migrations.AlterField(
            model_name='event',
            name='charity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.charity'),
        ),
    ]
